### PR TITLE
LPS-98497 SF

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Heyu @rgusztus 

Can you check my changes in the pr?

If works as expected, send it to @adolfopa.

Feel free to change it if you find any error.

Thanks!!

**Comment by robertoDiaz** [comment]
Oh, this is your first PR!

Congrats 🥇

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79643

**Comment by adolfopa** [comment]
Hey guys,

I ended up implementing a much simpler solution. That user id is always (and only) used for the sake of permission checking, so we should always use the current user id.

I've tested it and everything seems to work fine. Let me know if I missed some use case.

Thanks!

**Comment by adolfopa** [comment]
Hey guys, can you close this PR? Thanks!

**Pull request closed without merging**
